[config]
schemaVersion = "0.0.1"

[package]
namespace = "Conductor"
name = "FullClan"
versionNumber = "0.2.0"
description = "Allows you to play with the same clan as primary and allied"
websiteUrl = "https://github.com/Monster-Train-2-Modding-Group/FullClan"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
MT2-Trainworks_Reloaded = "0.4.1"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./"

[[build.copy]]
source = "./plugin_build"
target = ""

[publish]
repository = "https://thunderstore.io"
communities = [ "monster-train-2" ]


